# カスタマイズのタスク設定 https://github.com/ansistrano/deploy#role-variables
ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/roles/api/tasks/stop.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/api/tasks/start.yml"
